# Dataset Collection

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings(action = "ignore")

In [2]:
ccfd = pd.read_csv(r"C:\Users\KIIT\Downloads\archive (4)\creditcard.csv")
ccfd

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [3]:
ccfd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

# Data cleaning and processing

In [4]:
ccfd.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

distribution of legit and fraudulent transactions

In [5]:
ccfd['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [6]:
#class = 1 means fraud
#unbalanced dataset

Separation of data for analysis

In [7]:
legit = ccfd[ccfd.Class == 0]
fraud = ccfd[ccfd.Class == 1]

In [9]:
legit.shape

(284315, 31)

In [10]:
fraud.shape

(492, 31)

In [11]:
#statistical measures

In [12]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [14]:
#comparing values for both

In [15]:
ccfd.groupby('Class').mean() 
#gives mean of all columns

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Under Sampling - 
1. Build sample dataset containing similar distribution of legit transaction and fraudulent transaction
Number of fraud trans = 492

In [17]:
legitsample = legit.sample(n=492) #random sampling

In [18]:
#concatenating two dataframes

In [21]:
new_dataset = pd.concat([legitsample,fraud],axis=0) #axis =0 data frames added one by one row wise if 1 then column wise added

In [22]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
110999,72054.0,-6.874321,-14.465573,-3.710753,2.851992,-5.469470,2.136148,4.219244,-0.674539,-0.432859,...,2.603583,-1.969197,-3.723388,-0.098561,-1.262768,-0.657391,-0.738331,0.740556,4229.51,0
53401,45959.0,1.283963,-1.375720,0.739568,-1.429502,-1.647815,0.020112,-1.335246,0.119343,-1.889970,...,0.060744,0.444196,-0.044047,0.030198,0.218720,-0.098947,0.052917,0.025699,79.00,0
102975,68445.0,1.303895,0.292139,-0.302777,0.313148,0.539136,0.212196,0.019479,-0.005738,0.046659,...,-0.343576,-0.933698,-0.024142,-1.354209,0.345925,0.208779,-0.005881,0.015053,6.05,0
119049,75313.0,1.157336,0.115276,0.676867,0.714120,-0.644635,-0.845013,-0.050631,-0.052951,0.139644,...,-0.198354,-0.611493,0.232751,0.577161,0.039020,0.093091,-0.019869,0.021027,12.99,0
223859,143554.0,-0.434790,-0.299860,1.340094,-0.583806,0.649532,-0.666156,0.955106,-0.838655,1.196830,...,0.079859,1.186507,0.229440,-0.091912,-0.230305,-0.713070,-0.477635,-0.678843,30.60,0

In [23]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [24]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97372.040650,-0.034519,-0.052333,0.051848,-0.106379,-0.043157,0.053507,-0.011548,0.070240,0.003434,...,-0.020230,-0.010403,-0.072236,0.002502,0.039731,-0.000539,0.036606,-0.022056,-0.004149,87.616504
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting data into Features and targer

In [25]:
X = new_dataset.drop(columns = 'Class' ,axis = 1) #dropping columns
Y = new_dataset['Class']

In [26]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
110999,72054.0,-6.874321,-14.465573,-3.710753,2.851992,-5.469470,2.136148,4.219244,-0.674539,-0.432859,...,8.559170,2.603583,-1.969197,-3.723388,-0.098561,-1.262768,-0.657391,-0.738331,0.740556,4229.51
53401,45959.0,1.283963,-1.375720,0.739568,-1.429502,-1.647815,0.020112,-1.335246,0.119343,-1.889970,...,-0.194160,0.060744,0.444196,-0.044047,0.030198,0.218720,-0.098947,0.052917,0.025699,79.00
102975,68445.0,1.303895,0.292139,-0.302777,0.313148,0.539136,0.212196,0.019479,-0.005738,0.046659,...,-0.025621,-0.343576,-0.933698,-0.024142,-1.354209,0.345925,0.208779,-0.005881,0.015053,6.05
119049,75313.0,1.157336,0.115276,0.676867,0.714120,-0.644635,-0.845013,-0.050631,-0.052951,0.139644,...,-0.177086,-0.198354,-0.611493,0.232751,0.577161,0.039020,0.093091,-0.019869,0.021027,12.99
223859,143554.0,-0.434790,-0.299860,1.340094,-0.583806,0.649532,-0.666156,0.955106,-0.838655,1.196830,...,-0.205027,0.079859,1.186507,0.229440,-0.091912,-0.230305,-0.713070,-0.477635,-0.678843,30.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [27]:
Y

110999    0
53401     0
102975    0
119049    0
223859    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [28]:
#splitting into training and testing data

In [29]:
X_train,X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify = Y,random_state = 2)

In [30]:
X.shape

(984, 30)

In [31]:
X_train.shape #80%

(787, 30)

In [32]:
X_test.shape #20%

(197, 30)

Model Training
Logistic regression for binary classification

In [33]:
model = LogisticRegression()

In [34]:
#training the modelwith training data

In [35]:
model.fit(X_train,Y_train) #X_train = features Y_train = corresponding labels

LogisticRegression()

In [36]:
#Model evaluation based on accuracy score

In [37]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train) #compare values predicted

In [38]:
print('Accuracy on training data: ',training_data_accuracy)

Accuracy on training data:  0.9237611181702668

In [39]:
#92.3% is good accuracy score

In [41]:
#Accuracy score on test data(imp)

In [44]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [45]:
print('Accuracy score of test data: ',test_data_accuracy)

Accuracy score of test data:  0.8934010152284264

In [46]:
#accuracy score is 89.3% nearly same to training data

In [47]:
#overfitting and underfitting has not happened

In [49]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mse = mean_squared_error(X_test_prediction,Y_test)
r2 = r2_score(X_test_prediction,Y_test)

print('mse',mse)
print('r2',r2)

mse 0.1065989847715736
r2 0.5696004993757803